### ISSUE TITLE
Where should I add background.js file?

### ISSUE THREAD

**Issue by ijunc2** [penrodlol/demo-nextjs-browser-extension#1]

**Comment by penrodlol** [comment]
@ijunc2 I assume your referring to a [background script](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background)?

In that case, you can add it right under your _/public_ directory. Make sure to also add the ref to it within your manifest.json:
```json
  "background": {
    "scripts": ["background.js"]
  }
```

Hopefully that helps 😄 If not, please let me know.
